server:
  port: 8081

spring:
  application:
    name: CLOUDPROVIDER-8081
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study_data?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 2019ZF@123
    dbcp2:
      min-idle: 5             #数据库连接池最小的维持连接数
      max-total: 10           #最大连接数
      initial-size: 5         #初始化连接数
      max-wait-millis: 200    #等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #mapper映射文件
#  configuration:
#    map-underscore-to-camel-case: true #开启驼峰命名法
  type-aliases-package: com.gpf.*.entities

#eureka配置
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8000/eureka
      defaultZone: http://172.16.1.137:8000/eureka/,http://172.16.1.36:8001/eureka/
  instance:
    instance-id: cloudProvider_8081 #服务名称
    prefer-ip-address: true #访问路径显示ip地址


info:
  app.name: gpf-springcloud
  company.name: xingsibo
  build.artifactId: cloud-provider
  build.version: 1.0-SNAPSHOT
